Feature(oidc): add oidc sync job、use dcc public configure
masastack/MASA.Auth pull request #286
Opened 2022-08-26 05:29 UTC by 15168440402

2022-08-29 05:14 UTC, MayueCif commented on src/Services/Masa.Auth.Service.Admin/Application/Sso/CommandHandler.cs
> +
remove blank line

2022-08-29 05:16 UTC, MayueCif commented on src/Services/Masa.Auth.Service.Admin/Infrastructure/Extensions/SchedulerJobServiceCollectionExtensions.cs
> +        {
add log

2022-08-29 05:20 UTC, MayueCif commented on src/Web/Masa.Auth.Web.Admin.Server/Program.cs
> +using Masa.Utils.Security.Authentication.OpenIdConnect;
global using

2022-08-29 05:26 UTC, MayueCif requested changes
@15168440402

2022-08-30 06:33 UTC, doddgu requested changes

2022-08-30 06:33 UTC, doddgu commented on src/Services/Masa.Auth.Service.Admin/Program.cs
> +//#if DEBUG
?

2022-08-30 06:33 UTC, doddgu commented on src/Services/Masa.Auth.Service.Admin/Program.cs
> +builder.Services.AddPmClient(publicConfiguration.GetValue<string>("$public.AppSettings:PmClient:Url"));
Why both . and : ?

2022-08-30 07:54 UTC, doddgu approved these changes
LGTM

2022-08-30 07:54 UTC, merged