feature:modify department service and department razor page
masastack/MASA.Auth pull request #7
Opened 2022-03-29 03:45 UTC by MayueCif

2022-03-29 05:48 UTC, doddgu reviewed
@capdiem

2022-03-29 05:48 UTC, doddgu commented on src/ApiGateways/Masa.Auth.ApiGateways.Caller/Services/Organizations/DepartmentService.cs
> +    string baseUrl = "api/department";
_baseUrl

2022-03-29 05:48 UTC, doddgu commented on src/Services/Masa.Auth.Service.Admin/Application/Organizations/CommandHandler.cs
> +    public async Task AddDepartmentAsync(AddDepartmentCommand createDepartmentCommand)
AddDepartmentCommand createDepartmentCommand?

2022-03-29 05:48 UTC, doddgu commented on src/Services/Masa.Auth.Service.Admin/Application/Organizations/CommandHandler.cs
> +        if (dto.Id == Guid.Empty)
1. Abstract a `BaseUpsertDto` or `BaseAddOrUpdateDto`
2. Add `InferredAction` help determine whether to add or update, maybe you need JsonIgnore this property
3. Finally, use switch or if/else process logic

2022-03-29 10:57 UTC, doddgu commented on src/Contracts/Masa.Auth.Contracts.Admin/Infrastructure/Dtos/BaseUpsertDto.cs
> +    public bool HasValue => Id.Equals(default(T));
HasValue????

2022-03-29 11:25 UTC, doddgu reviewed
LGTM

2022-03-29 11:55 UTC, capdiem requested changes

2022-03-29 11:55 UTC, capdiem commented on src/Web/Masa.Auth.Web.Admin.Rcl/Pages/Organization/OrgSheet.razor
> +            <MTextField @bind-Value="@Dto.Name" class="mx-auto text-h5 .neutral-lighten-4--text" HideDetails="@("auto")" style="width:323px;" Placeholder="@T("Enter department name")"></MTextField>
.neutral-lighten-4--text? .?

2022-03-29 11:55 UTC, capdiem commented on src/Web/Masa.Auth.Web.Admin.Rcl/Pages/Organization/Organization.razor
> +                                                <MListItem OnClick="async ()=> await Copy(context.Item.Id)">
这里可以省略async await?

2022-03-29 11:55 UTC, capdiem commented on src/Web/Masa.Auth.Web.Admin.Rcl/Pages/Organization/Organization.razor.cs
> +
多了个空行。

2022-03-30 04:55 UTC, capdiem approved these changes
LGTM. @doddgu

2022-03-30 05:06 UTC, merged