feature:add team blazor page and service (undo teamrole and teampermission).
masastack/MASA.Auth pull request #8
Opened 2022-03-31 10:52 UTC by MayueCif

2022-03-31 11:27 UTC, doddgu commented on src/ApiGateways/Masa.Auth.ApiGateways.Caller/Services/Subjects/TeamService.cs
> +﻿using Microsoft.AspNetCore.Mvc;
Why using mvc?

2022-03-31 11:27 UTC, doddgu commented on src/Contracts/Masa.Auth.Contracts.Admin/Organizations/UpsertDepartmentDto.cs
> +
Why add a blank line.

2022-03-31 11:27 UTC, doddgu commented on src/Contracts/Masa.Auth.Contracts.Admin/Subjects/TeamDetailDto.cs
> +﻿using System.ComponentModel;
global using

2022-03-31 11:27 UTC, doddgu commented on src/Contracts/Masa.Auth.Contracts.Admin/Subjects/UpdateTeamBaseInfoDto.cs
> +public class UpdateTeamBaseInfoDto
BasicInfo

2022-03-31 11:27 UTC, doddgu commented on src/Contracts/Masa.Auth.Contracts.Admin/Subjects/UpdateTeamPersonnelDto.cs
> +public class UpdateTeamPersonnelDto
Personnel -> Member?

2022-03-31 11:27 UTC, doddgu commented on src/Services/Masa.Auth.Service.Admin/Application/Subjects/CommandHandler.cs
> +    public async Task UpdateTeamBaseInfoAsync(UpdateTeamBaseInfoCommand updateTeamBaseInfoCommand)
BasicInfo

2022-03-31 11:27 UTC, doddgu commented on src/Services/Masa.Auth.Service.Admin/Application/Subjects/CommandHandler.cs
> +            throw new UserFriendlyException("the team has staffs can`t delete");
Capitalize the first letter of a sentence

2022-03-31 11:27 UTC, doddgu commented on src/Services/Masa.Auth.Service.Admin/Application/Subjects/Commands/UpdateTeamBaseInfoCommand.cs
> +public record UpdateTeamBaseInfoCommand(UpdateTeamBaseInfoDto UpdateTeamBaseInfoDto) : Command
BasicInfo

2022-03-31 11:27 UTC, doddgu commented on src/Services/Masa.Auth.Service.Admin/Application/Subjects/Commands/UpdateTeamPersonnelCommand.cs
> +public record UpdateTeamPersonnelCommand(UpdateTeamPersonnelDto UpdateTeamPersonnelDto, TeamMemberTypes MemberType) : Command
Member

2022-03-31 11:27 UTC, doddgu commented on src/Web/Masa.Auth.Web.Admin.Rcl/Pages/Organization/CopyOrgSheet.razor
> +                    <MButton class="rounded-pill primary" MinWidth="100" Disabled="@string.IsNullOrEmpty(Dto.Name.Trim())" OnClick="OnSubmitHandler">@T("Submit")</MButton>
IsNullOrWhiteSpace

2022-03-31 11:27 UTC, doddgu commented
@capdiem

2022-04-01 03:02 UTC, capdiem requested changes

2022-04-01 03:02 UTC, capdiem commented on src/Web/Masa.Auth.Web.Admin.Rcl/Pages/Subjects/Teams/TeamMember.razor
> +                    @((MarkupString)data.Item.Name)
MarkupString again?

2022-04-01 03:02 UTC, capdiem commented on src/Web/Masa.Auth.Web.Admin.Rcl/Pages/Subjects/Teams/UpdateSheet.razor.cs
> +        Dto.TeamBaseInfo.PropertyChanged += (sender, args) => StateHasChanged();
不建议使用PropertyChanged

2022-04-01 04:43 UTC, MayueCif commented on src/Web/Masa.Auth.Web.Admin.Rcl/Pages/Subjects/Teams/AddSheet.razor.cs
> +        _teamDetailDto.TeamBaseInfo.PropertyChanged += (sender, args) => StateHasChanged();
意见不统一 待定修改方案

2022-04-01 04:43 UTC, MayueCif commented on src/Web/Masa.Auth.Web.Admin.Rcl/Pages/Subjects/Teams/UpdateSheet.razor.cs
> +        Dto.TeamBaseInfo.PropertyChanged += (sender, args) => StateHasChanged();
意见不统一 待定修改方案

2022-04-01 08:42 UTC, doddgu reviewed
LGTM

2022-04-02 02:55 UTC, capdiem approved these changes
LGTM. @doddgu

2022-04-02 03:43 UTC, doddgu approved these changes
LGTM

2022-04-02 03:43 UTC, merged